#ifndef BULLETINVERSEDYNAMICSAPI_H
#define BULLETINVERSEDYNAMICSAPI_H

#include "bullet3Api.h"

#ifdef BulletInverseDynamics_EXPORTS
#define BULLETINVERSEDYNAMICS_API BULLET_EXPORT
#else
#define BULLETINVERSEDYNAMICS_API BULLET_IMPORT
#endif

#endif
