#ifndef BULLET2FILELOADERAPI_H
#define BULLET2FILELOADERAPI_H

#include "bullet3Api.h"

#ifdef Bullet2FileLoader_EXPORTS
#define BULLET2FILELOADER_API BULLET_EXPORT
#else
#define BULLET2FILELOADER_API BULLET_IMPORT
#endif

#endif
